---
title: "Untitled"
author: "riley wares"
date: "2026-03-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
#install.packages("pacman")
library(pacman)
pacman::p_load(tidyverse, here, cowplot, emmeans)
```

```{r import datasets}
beetle_litter <- read.csv(here("data", "processed", "beetle_litter_joined_table"))

```


```{r graph by site}
beetle_litter_model2 <- lm(avg_richness_plotmonth ~ (avg_mass_plotmonth), data=beetle_litter) 
beetle_litter_model <- aov(avg_richness_plotmonth ~ (avg_mass_plotmonth) * siteID, data=beetle_litter) 
summary(beetle_litter_model)
summary(beetle_litter_model2)
plot(beetle_litter_model, which=1:3)

ggplot(beetle_litter_model, aes(x=avg_mass_plotmonth, y=avg_richness_plotmonth, color=siteID)) +
  geom_point(dotsize=0.5) +
  geom_smooth(method="lm")


em <- emmeans(beetle_litter_model, ~siteID)
tukey_beetle_litter <- contrast(em, method="pairwise", adjust="Tukey")
summary(tukey_beetle_litter, infer=TRUE, level=0.95)
```